
package com.parameta.employee.infrastructure.web_services;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeesPortService", targetNamespace = "http://www.springframework.org/schema/web-services", wsdlLocation = "http://localhost:8080/ws/employees.wsdl")
public class EmployeesPortService
    extends Service
{

    private final static URL EMPLOYEESPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESPORTSERVICE_EXCEPTION;
    private final static QName EMPLOYEESPORTSERVICE_QNAME = new QName("http://www.springframework.org/schema/web-services", "EmployeesPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/employees.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESPORTSERVICE_WSDL_LOCATION = url;
        EMPLOYEESPORTSERVICE_EXCEPTION = e;
    }

    public EmployeesPortService() {
        super(__getWsdlLocation(), EMPLOYEESPORTSERVICE_QNAME);
    }

    public EmployeesPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESPORTSERVICE_QNAME, features);
    }

    public EmployeesPortService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESPORTSERVICE_QNAME);
    }

    public EmployeesPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESPORTSERVICE_QNAME, features);
    }

    public EmployeesPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeesPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeesPort
     */
    @WebEndpoint(name = "EmployeesPortSoap11")
    public EmployeesPort getEmployeesPortSoap11() {
        return super.getPort(new QName("http://www.springframework.org/schema/web-services", "EmployeesPortSoap11"), EmployeesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeesPort
     */
    @WebEndpoint(name = "EmployeesPortSoap11")
    public EmployeesPort getEmployeesPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.springframework.org/schema/web-services", "EmployeesPortSoap11"), EmployeesPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESPORTSERVICE_EXCEPTION!= null) {
            throw EMPLOYEESPORTSERVICE_EXCEPTION;
        }
        return EMPLOYEESPORTSERVICE_WSDL_LOCATION;
    }

}
