
package com.parameta.employee.infrastructure.web_services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeesPort", targetNamespace = "http://www.springframework.org/schema/web-services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeesPort {


    /**
     * 
     * @param getEmployeeRequest
     * @return
     *     returns org.springframework.schema.web_services.GetEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "getEmployeeResponse", targetNamespace = "http://www.springframework.org/schema/web-services", partName = "getEmployeeResponse")
    public GetEmployeeResponse getEmployee(
        @WebParam(name = "getEmployeeRequest", targetNamespace = "http://www.springframework.org/schema/web-services", partName = "getEmployeeRequest")
        GetEmployeeRequest getEmployeeRequest);

    /**
     * 
     * @param saveEmployeeRequest
     * @return
     *     returns org.springframework.schema.web_services.SaveEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "saveEmployeeResponse", targetNamespace = "http://www.springframework.org/schema/web-services", partName = "saveEmployeeResponse")
    public SaveEmployeeResponse saveEmployee(
        @WebParam(name = "saveEmployeeRequest", targetNamespace = "http://www.springframework.org/schema/web-services", partName = "saveEmployeeRequest")
        SaveEmployeeRequest saveEmployeeRequest);

}
